### ISSUE TITLE
Midterm Review Question

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3410/docs#1]
I am having trouble with this question:
![screen shot 2017-10-17 at 4 14 15 pm](https://user-images.githubusercontent.com/25493211/31687093-4daa296e-b356-11e7-9b16-70809f8c88fe.png)
The State space in this instance is all the possible positions the robot could occupy within the maze, correct? I do not understand how the observation in section B of the problem would change that the state space is all possible positions of the robot within the maze.  Are they looking for an answer along the lines of, if a corridor is a dead end, then do not explore that path or something like that?
@rivlev

**Comment by MichaelGregg** [comment]
My next question is about Question #6 on the practice exam.  This is copied from your answer for the proof section of the question: 
![fullsizerender](https://user-images.githubusercontent.com/25493211/31690060-871e2840-b35f-11e7-9f8e-35c257295894.jpg)
@rivlev Could you please in as simple terms as possible explain lines two through six?

**Comment by MichaelGregg** [comment]
Lastly,
![screen shot 2017-10-17 at 6 00 48 pm](https://user-images.githubusercontent.com/25493211/31691764-31bdb4a0-b365-11e7-96b3-61f6524c986f.png)
I think i understand the concept, but could you or someone please give me the answers for this question? I could not copy them fast enough in class.
@rivlev

**Comment by h01m3s** [comment]
1. A: 4, B: 4, C: 3, D: 4
2. c2 and c3
3. Either B node or D node.

**Comment by MichaelGregg** [comment]
@h01m3s Thanks.  Why do nodes C2 and C3 not need to be evaluated? The inner node C, since it has a triangle facing down is supposed to find the minimum value between nodes c1 c2 and c3 so why wouldn't all three (c1 c2 and c3) be evaluated?

**Comment by h01m3s** [comment]
@MichaelGregg Because you got B <= 4, and the first evaluation of C makes C <= 3. A will chose the max between B: 4 and C <= 3, and it won chose C anyway. So there's no meaning to evaluate C node further more.

**Comment by MichaelGregg** [comment]
@h01m3s Got it thanks

**Comment by rivlev** [comment]
State space: since the only real decisions need to be made at intersections, we can abstract away intermediate positions and only consider positions at intersections.  This vastly reduces the state space.

Resolution: When you have two OR clauses (clauses containing only OR connectors) ANDed together (connected by AND), you can collapse them into one OR clause if one contains the negation of a proposition in the other one.

E.g. ```(A or B) and (not A or C or D or E) --> (B or C or D or E)```

A is knocked out by its complement, and the remaining propositions are joined together in one OR clause.

```(not H or M) and (not M)```: ```M``` is knocked out by ```not M``` in the other clause, leaving only ```not H```

similar for lines 2-5

line 6 is the same, but in this case M was the only thing in its clause, so knocking it out with ```not M``` leaves an empty clause, which means that the knowledge base is inherently inconsistent

which means that ```not M```, which we tried to add to the knowledge base, can't be true, which means that ```M``` must be true.

**Comment by MichaelGregg** [comment]
@rivlev thank you.  I think i am now understanding the proof in list form.  If we will be expected to do something like this on the midterm:
![screen shot 2017-10-17 at 8 52 12 pm](https://user-images.githubusercontent.com/25493211/31696130-3bf77506-b37d-11e7-918e-d3d330e97612.png), then could you explain how it was constructed? i understand the blue section (CNF conversions) but i do not understand the rest

**Comment by rivlev** [comment]
A pair of clauses connected by a pair of edges leading to a new clause is the equivalent of one item on the list.

e.g. ```not W or H``` and ```W``` are the parents of ```H``` is a graphical representation of ```not W or H and W becomes H```

You will not need to specifically create a diagram like this.
